# netlify.toml
[build]
  command   = "npm run build"
  publish   = ".next"           # Netlify will serve from here
  functions = ".netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
